# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
# Edit here

# Site settings
title: Gauri Jhangiani
email: gaurijhangiani@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for SEO optimization) and in your feed.xml site description.
baseurl: "" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "gaurijhangiani.github.io" # change this to the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Make sure to exclude 'vendor' from the build
exclude: [vendor, "Gemfile", "Gemfile.lock"]

# permalink: /:categories/:year/:month/:day/:title.html
# none is equivalent to /:title.html
# https://jekyllrb.com/docs/permalinks
permalink: /:title.html

# jekyll-theme-simple-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
jekyll-theme-simple-blog:
  date_format:

theme: # leave it empty

header_page_refs: ['coding','projects','about']

plugins:
  - jekyll-target-blank

target-blank:
    rel: nofollow

show_post_image_posts_list: false

header:
  image: /assets/patterns/symphony.png

# social
author:
  name: "Gauri Jhangiani"
  short_bio:
    en: Author of The Extraordinary Lives of Ordinary People
  picture: assets/img/profile-60.png

image: /assets/img/profile-225.png

#twitter:
#  username:
#instagram_username:

linkedin_username: gauri-jhangiani-826baa134

# github on site
github:
  owner_url: https://github.com/gaurijhangiani


  en:
    latest-posts:  "Latest Posts"
    read-more:  "Read More →"
    show-more:  "Show More →"
    loading:  "Loading..."
    on-word: "on"
    contact: "Contact"
    contact-page: "contact.md"
    read-time: "min read"
    comments: "comments"
    go-to-home-page: "Go to the Home Page"
    months:
      january: "Jan"
      february: "Feb"
      march: "Mar"
      april: "Apr"
      may: "May"
      june: "Jun"
      july: "Jul"
      august: "Aug"
      september: "Sep"
      october: "Oct"
      november: "Nov"
      december : "Dec"
defaults:
  -
    scope:
      type: "posts"
    values:
      lang: "en"
      category: articles
